_target_: pangaea.encoders.croma_encoder.CROMA_SAR_Encoder
encoder_weights: ./pretrained_models/CROMA_large.pt
download_url: https://huggingface.co/antofuller/CROMA/resolve/main/CROMA_large.pt

input_size: 120  # the paper uses 120
size: 'large'

input_bands:
  sar:
    - VV
    - VH

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 1024