
_target_: pangaea.encoders.satlasnet_encoder.SatlasNet_Encoder
encoder_weights: null
download_url: null
model_identifier: Sentinel2_SwinB_MI_MS # Multi-Image Multi-Spectral 
fpn: False
input_size: 128

input_bands:
  optical:
    # - B4
    # - B3
    # - B2

    #MS Bands 
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B11
    - B12

output_layers:
  - 0
  - 1
  - 2
  - 3

output_dim:
  - 128
  - 256
  - 512
  - 1024