name: Bandit security checks

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  run-bandit:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
